<?php

/**
 * @file
 * Contains superdrupal.module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function superdrupal_theme() {
  $themes['superdrupal_base'] = array(
    'variables' => array('data' => array()),
  );

  $themes['superdrupal_profile'] = array(
    'render element' => 'elements',
  );

  $themes['superdrupalreach'] = [
    'template' => 'superdrupalreach',
    'variables' => [
      'data' => NULL,
    ],
  ];

  return $themes;
}

/**
 * Implements template_preprocess_theme().
 */
function template_preprocess_superdrupal_profile(&$variables) {
  $variables['super_profile'] = $variables['elements']['#super_profile'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

